### ISSUE TITLE
HTTP Server base URL

### ISSUE THREAD

**Issue by wirachai** [gabrie-allaigre/sonar-auth-gitlab-plugin#10]
Cloud it has some configuration to enable HTTP access for internal IP access?

As explained in configuration section on the first page, this plugin required HTTPS access,
but I think it doesn't make sense for a small team that has no HTTPS implementation.

**Comment by gabrie-allaigre** [comment]
Hi,
See https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin/issues/8

**Comment by wirachai** [comment]
Thanks
