### ISSUE TITLE
Fail to initialize authentication with provider 'gitlab'

### ISSUE THREAD

**Issue by chengxing** [gabrie-allaigre/sonar-auth-gitlab-plugin#14]
2017.12.22 21:13:13 ERROR web[AWB9+Q3yf6pNrHleAADN][o.s.s.a.AuthenticationError] Fail to initialize authentication with provider 'gitlab'
org.sonar.api.utils.MessageException: The server url should be configured in https, please update the property 'sonar.core.serverBaseURL'

May I ask how to solve this problem？SonarQube is https.（https://sonarqube.jiedaibao.com/sessions/unauthorized）
Is that I given incorrect ApplicatID and secret for Gitlab？

**Comment by gabrie-allaigre** [comment]
Hi,
Have you set Server base URL in SonarQube -> Administration -> General > Server base URL ?

**Comment by chengxing** [comment]
yes,I have set...
