### ISSUE TITLE
Groups are reset

### ISSUE THREAD

**Issue by h4wkmoon** [gabrie-allaigre/sonar-auth-gitlab-plugin#16]
Hi, 
and thanks for this plugins. It is very helpfull.

I've just made the upgrade. I think there is a small regression.

Groups are all reset each time the user logs in. Each time a user logs, he loses his rights.
Adding the user in the "keep intact" list works, but I can't add all my users to this list.
(The group sync with gitlab is not activated.)

**Comment by gabrie-allaigre** [comment]
Hi,
I see, thanks

**Comment by gabrie-allaigre** [comment]
Sorry for problems.
I fix a problems with 1.3.1-rc1

For now you can add the default groups in field `groups`

**Comment by h4wkmoon** [comment]
No worries. I'll wait for the fix. Thanks for your quick answer.
I would have helped but java is not my strong suit. (far from it)

**Comment by gabrie-allaigre** [comment]
Fix with release https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin/releases/tag/1.3.1

You have to wait for it to be on the marketplace

**Comment by h4wkmoon** [comment]
that was quick !
Works like a charm.
Thanks a lot.

**Comment by h4wkmoon** [comment]
Bug is back with 1.3.2

**Comment by h4wkmoon** [comment]
My bad. I did a wrong config.
Sorry.
