### ISSUE TITLE
Unable to login into SonarQube 6.7

### ISSUE THREAD

**Issue by hervedevos** [gabrie-allaigre/sonar-auth-gitlab-plugin#17]
Hello,

Iam not able to log into SonarQube with the plugin and Gitlab OAuth enabled.

Here is my configuration :
**Versions**:
- SonarQube 6.7
- sonar-auth-gitlab-plugin v1.3.0
- Gitlab 10.1.5

**Gitlab configuration**
System OAuth applications:
- Name : SonarQube
- URL : https://my-sonarqube-domain/oauth2/callback/gitlab
- Trusted : Yes
- Scope : read_user

**SonarQube Configuration**
SonarQube :
- sonar.core.serverBaseURL : https://my-sonarqube-domain

Gitlab :
- GitlabURL : https://my-gitlab-domain/gitlab
- Application ID : application ID from Gitlab OAuth application
- Secret : secret from Gitlab OAuth application
- Gitlab access scope : read_user

**Additional information**
- SSL certificates are valid certificates (for both my-gitlab-domain and my-sonarqube-domain)
- Gitlab OAuth login is working well with Jenkins gitlab-oauth-plugin in same configuration
- I tested with scope api and get the same result
- If i deactivate "trusted : yes", I go through gitlab Oauth service validation page

**Stack trace**
When request is sended back from Gitlab and going through https://my-sonarqube-domain/oauth2/callback/gitlab :

[o.s.s.a.AuthenticationError] Fail to callback authentication with 'gitlab'
com.github.scribejava.core.exceptions.OAuthException: Cannot extract an access token. Response was: {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
at com.github.scribejava.core.extractors.JsonTokenExtractor.extractAccessToken(JsonTokenExtractor.java:24)
at com.github.scribejava.core.extractors.JsonTokenExtractor.extract(JsonTokenExtractor.java:15)
at com.github.scribejava.core.oauth.OAuth20ServiceImpl.getAccessToken(OAuth20ServiceImpl.java:37)

From my understanding, the issue seems linked to Gitlab response ("error":"invalid_client"), but as my configuration seems valid to me, I don't get why gitlab is sending such a response ? Did you already encounter this issue ?

**Comment by gabrie-allaigre** [comment]
Hi,
Have you good copy for application ID in SonarQube ?

**Comment by hervedevos** [comment]
Hi,

I debuggued access token creation (OAuth20ServiceImpl.createAccessTokenRequest) and found out that all fields are OK and aligned with Gitlab configuration - including authorization code previously retrieved (CLIENT_ID, CLIENT_SECRET, CODE, REDIRECT_URI, SCOPE, GRANT_TYPE), but POST request made to /gitlab/oauth/token to get the access token end up with a 401 response

Im now going through Gitlab debug to get further information

**Comment by gabrie-allaigre** [comment]
Ok thanks 
I use GitLab 10.3.2 and work.

**Comment by hervedevos** [comment]
I had a DNS issue in my sonarqube container :  I was going out of my containers to get back into nginx container (internet request)... (nginx container exposing both sonarqube container / gitlab container)

Issue is solved when setting public DNS to avoid going outside my containers (i suppose I was loosing some headers while going outside)

**Comment by gabrie-allaigre** [comment]
Good, Thanks
