### ISSUE TITLE
login sequence switches to internal name (mini-docker network)

### ISSUE THREAD

**Issue by john-forrest** [gabrie-allaigre/sonar-auth-gitlab-plugin#23]
I'm trying to use a small docker network to implement http proxing. I have three containers: nginx (for the proxy), sonarqube itself and a postgresql for the database. The nginx proxy maps https 9000 to http 9000 for sonarqube. It also maps 9092 since I'm not sure if I need it or not! http access from outside this mini network is banned. 

So far so good. However I'm trying to get login via working - that was much of the motivation of using https at this point, although we'd probably have to anyway. I've set it up and can go through the sequence, however at the key point the browser complains it cannot find "sonarqube" and appears to have failed the login. However I notice it has actually logged me in using my gitlab username and the issue is I think (slightly guessing) that a redirect to take me back to sonarqube fails.

Internally to the docker network, so sonarqube container is named "sonarqube" and http://sonarqube:9000 works. Externally the URL is a proper "internal" URL - it can be used behind our firewall but not externally.

I have set the "Server base URL" to be the properly qualified external name, including https and 9000, but my guess is that this plugin is somehow using the internal computer name instead. Is there some way of finding out?

**Comment by tsmgeek** [comment]
I had the same issue, you need to change `sonar.core.serverBaseURL` in general app settings. to the public hostname of sonar.

**Comment by john-forrest** [comment]
I got this to work, but can't remember exactly how:) However think it relates to nginx using below. Key one was first line which meant that an access to http was redirected to try as https.

    error_page 497 https://$host:$server_port$request_uri;

    client_max_body_size 20M; # allow large postings

    location / {
        proxy_pass http://sonarqube:9000;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect  http://sonarqube:9000/ $scheme://$host:$server_port/;
    }
