### ISSUE TITLE
The redirect URI included is not valid.

### ISSUE THREAD

**Issue by tmc9031** [gabrie-allaigre/sonar-auth-gitlab-plugin#29]
gitlab version: 11.5
sonar version: 7.4
plugin version: 1.3.2

i config sonar http 9000 behind nginx https 433 for plugin https limit
but after open sonar https url and login with gitlab, i return ：The redirect URI included is not valid.
i found the url become localhost:9000 it is wrong, but i do NOT know whether it is plugin problem
    http://mygitlab.com/oauth/authorize?client_id=xxxxxxxxxxxx&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Foauth2%2Fcallback%2Fgitlab&response_type=code&scope=read_user

my gitlab config

    Callback URL https://mysonar.com:8443/oauth2/callback/gitlab

my nginx config

    server {
    server_name  mysonar.com;
    listen              8443 ssl;
    location / {
        proxy_pass http://172.20.0.3:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X_FORWARDED_PROTO: https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

**Comment by daniel-ng** [comment]
I had this same issue in my configuration. You are missing a baseurl config (Server base URL) in your Sonar General Settings. The key for this is sonar.core.serverBaseURL. Once that's set up, Gitlab will begin to redirect to the correct URL.

**Comment by tmc9031** [comment]
@daniel-ng thanks a lot, after config sonar.core.serverBaseURL then login work !!!

**Comment by qhh0205** [comment]
I have the same issue, but after set the sonar.core.serverBaseURL, the gitlab return 500...
![image](https://user-images.githubusercontent.com/12775142/50325288-eaebf200-051e-11e9-8c57-5e4b84943074.png)

**Comment by daniel-ng** [comment]
You may actually have a slightly different issue then. What are your logs telling you?

**Comment by qhh0205** [comment]
@daniel-ng Thansks for your reply, I found out the reason that not checked Trusted option when creating gitlab applications. After check the Trusted option, that worked. In addition, the http URL of sonar can also work when create gitlab application not just only https.
![image](https://user-images.githubusercontent.com/12775142/50369712-b20e5480-05d4-11e9-9f90-ba2b291aa7a4.png)

**Comment by rbkuscu** [comment]
It worked for me too when I wrote it in the format below.

http://xx.xx.xxx.xx:9000

![image](https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin/assets/119670848/628ce429-f108-4edf-b532-3aea192302a5)
