### ISSUE TITLE
The release url has a problem

### ISSUE THREAD

**Issue by flamhaze5946** [gabrie-allaigre/sonar-auth-gitlab-plugin#4]
For SonarQube >=5.6:

Download last version https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin/releases/download/1.2.0/sonar-auth-gitlab-plugin-1.2.1.jar
Copy file in extensions directory SONARQUBE_HOME/extensions/plugins
Restart SonarQube

the url could be  https://github.com/gabrie-allaigre/sonar-auth-gitlab-plugin/releases/download/1.2.1/sonar-auth-gitlab-plugin-1.2.1.jar

**Comment by gabrie-allaigre** [comment]
Thanks
