### ISSUE TITLE
Unable to start Sonarqube due to incompatibility in version

### ISSUE THREAD

**Issue by c0debreaker** [gabrie-allaigre/sonar-auth-gitlab-plugin#40]
Our Sonarqube 7.9.6 is using the plugin sonar-auth-gitlab-plugin-1.4.0-SNAPSHOT.jar.

When I upgraded it to 8.9.3, Sonarqube won't start anymore. The logs is saying

```
ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed: The following plugins are no longer compatible with this version of SonarQube: 'authgitlab', 'scmgit', 'scmsvn'
```

I am not sure which version of auth-gitlab plugin I should download.

**Comment by dennys** [comment]
I think Sonar 8.9 or above already have the ability to integrate to GitLab.
https://docs.sonarqube.org/latest/analysis/gitlab-integration/

**Comment by c0debreaker** [comment]
Ooops, I figured this out long time ago. I forgot what I did. And yes, you are correct @dennys!
