### ISSUE TITLE
incompatibility between Sonar 6.3.1 & gitlab 9.2.1

### ISSUE THREAD

**Issue by misterfifi1** [gabrie-allaigre/sonar-auth-gitlab-plugin#7]
Hi, 

I followed the installation guide, but I have an issue, I am always redirected to the page: {sonar.url}/sessions/unauthorized, with the message: "You're not authorized to access this page. Please contact the administrator."

In the sonar's "web.log"file, I can find the error message: "The request requires hier privileges than provided by the access token, scope : api."

I tried so add the "api" privilege to the application, in addition of the read_user but I still have the same issue. 

Could you help me?

Regards,

**Comment by zemzela** [comment]
When using a non CA certificate on your gitlab, you have to add the certificate to the java store.

**Comment by misterfifi1** [comment]
Hi, thanks for your quick reply, 

I followed your advice and added the cert in my OpenJDK keystore "alias <gitlab> already exists"

I rebooted the sonar server, but I still have the error (please find it below). 

Just to confirm, I created the application in : Admin area -> Application, is that correct?

java.lang.IllegalStateException: Fail to authenticate the user. Error code is 403, Body of the response is {"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api"}

Thanks for your help

**Comment by gabrie-allaigre** [comment]
Hi,
Sonar is https ?

**Comment by misterfifi1** [comment]
Hi, yes, both signed with https://letsencrypt.org/

**Comment by gabrie-allaigre** [comment]
Normally, the scope read_user is sufficient

**Comment by misterfifi1** [comment]
Honestly, it is very weird because when I try the connection, it asks only the Read user, but after the  failure, in the logs I have the message I provided.

**Comment by misterfifi1** [comment]
Hi, 

I installed the instance last night, so I have the latest version. 

The callback URL is: https://quality.{domain}/oauth2/callback/gitlab 

In the access log, I can find the right calls 

Regards,

**Comment by gabrie-allaigre** [comment]
No, URL call GitLab

https://gitlab.......

**Comment by misterfifi1** [comment]
Are you asking for this one?

<img width="559" alt="screen shot 2017-05-24 at 17 04 21" src="https://cloud.githubusercontent.com/assets/5573438/26410274/127c2a3e-40a3-11e7-8347-56d6a26c501f.png">

**Comment by misterfifi1** [comment]
I have question, in my past OAuth2 experiences, the scope was defined by the user when you create the application (here on gitlab), so why are you using the scope in the ServiceBuilder?

**Comment by gabrie-allaigre** [comment]
Hi, Thank you for the feedback

**Comment by zemzela** [comment]
Just to confirm that indeed there is an incompatibility between Sonar 6.3.1 & Gitlab 9.2.1.
The plugin worked fine before the update, so i changed the "Gitlab access scope" to api with 1.3.0 version and it works fine.

Regards

**Comment by gabrie-allaigre** [comment]
It may be a gitlab bug
https://gitlab.com/gitlab-org/gitlab-ce/issues/33022

**Comment by misterfifi1** [comment]
Hi, 

Thanks for the follow-up, I joined the thread, hope that will be fix soon (despite I have a workaround)

Regards,
